// Curated Database of 250+ Top DSA LeetCode Questions for Placement Preparation
// Grouped into 10 key technical patterns from basic structures to advanced optimization.

export const defaultDsaTopics = [
  {
    id: 'arrays',
    title: 'Arrays & Hashing',
    icon: 'grid_view',
    color: 'text-emerald-500 bg-emerald-50/50 dark:bg-emerald-950/20 border-emerald-100 dark:border-emerald-900/30',
    problems: [
      { id: 'arr1', name: 'Two Sum', difficulty: 'Easy', link: 'https://leetcode.com/problems/two-sum/' },
      { id: 'arr2', name: 'Contains Duplicate', difficulty: 'Easy', link: 'https://leetcode.com/problems/contains-duplicate/' },
      { id: 'arr3', name: 'Valid Anagram', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-anagram/' },
      { id: 'arr4', name: 'Group Anagrams', difficulty: 'Medium', link: 'https://leetcode.com/problems/group-anagrams/' },
      { id: 'arr5', name: 'Top K Frequent Elements', difficulty: 'Medium', link: 'https://leetcode.com/problems/top-k-frequent-elements/' },
      { id: 'arr6', name: 'Product of Array Except Self', difficulty: 'Medium', link: 'https://leetcode.com/problems/product-of-array-except-self/' },
      { id: 'arr7', name: 'Valid Sudoku', difficulty: 'Medium', link: 'https://leetcode.com/problems/valid-sudoku/' },
      { id: 'arr8', name: 'Longest Consecutive Sequence', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-consecutive-sequence/' },
      { id: 'arr9', name: 'Majority Element', difficulty: 'Easy', link: 'https://leetcode.com/problems/majority-element/' },
      { id: 'arr10', name: 'Find All Numbers Disappeared in an Array', difficulty: 'Easy', link: 'https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/' },
      { id: 'arr11', name: 'Intersection of Two Arrays II', difficulty: 'Easy', link: 'https://leetcode.com/problems/intersection-of-two-arrays-ii/' },
      { id: 'arr12', name: 'Single Number', difficulty: 'Easy', link: 'https://leetcode.com/problems/single-number/' },
      { id: 'arr13', name: 'Sort Colors', difficulty: 'Medium', link: 'https://leetcode.com/problems/sort-colors/' },
      { id: 'arr14', name: 'Subarray Sum Equals K', difficulty: 'Medium', link: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
      { id: 'arr15', name: 'Pascal Triangle', difficulty: 'Easy', link: 'https://leetcode.com/problems/pascals-triangle/' },
      { id: 'arr16', name: 'Next Permutation', difficulty: 'Medium', link: 'https://leetcode.com/problems/next-permutation/' },
      { id: 'arr17', name: 'Merge Sorted Array', difficulty: 'Easy', link: 'https://leetcode.com/problems/merge-sorted-array/' },
      { id: 'arr18', name: 'Remove Duplicates from Sorted Array', difficulty: 'Easy', link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/' },
      { id: 'arr19', name: 'Move Zeroes', difficulty: 'Easy', link: 'https://leetcode.com/problems/move-zeroes/' },
      { id: 'arr20', name: 'Spiral Matrix', difficulty: 'Medium', link: 'https://leetcode.com/problems/spiral-matrix/' },
      { id: 'arr21', name: 'Rotate Image', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotate-image/' },
      { id: 'arr22', name: 'Set Matrix Zeroes', difficulty: 'Medium', link: 'https://leetcode.com/problems/set-matrix-zeroes/' },
      { id: 'arr23', name: 'Grid Game', difficulty: 'Medium', link: 'https://leetcode.com/problems/grid-game/' },
      { id: 'arr24', name: 'Find Pivot Index', difficulty: 'Easy', link: 'https://leetcode.com/problems/find-pivot-index/' },
      { id: 'arr25', name: 'Encode and Decode Strings', difficulty: 'Medium', link: 'https://leetcode.com/problems/encode-and-decode-strings/' },
      { id: 'arr26', name: 'First Missing Positive', difficulty: 'Hard', link: 'https://leetcode.com/problems/first-missing-positive/' }
    ]
  },
  {
    id: 'pointers',
    title: 'Two Pointers & Sliding Window',
    icon: 'swap_horiz',
    color: 'text-blue-500 bg-blue-50/50 dark:bg-blue-950/20 border-blue-100 dark:border-blue-900/30',
    problems: [
      { id: 'ptr1', name: 'Valid Palindrome', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-palindrome/' },
      { id: 'ptr2', name: 'Two Sum II - Input Array Is Sorted', difficulty: 'Medium', link: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
      { id: 'ptr3', name: '3Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/3sum/' },
      { id: 'ptr4', name: 'Container With Most Water', difficulty: 'Medium', link: 'https://leetcode.com/problems/container-with-most-water/' },
      { id: 'ptr5', name: 'Trapping Rain Water', difficulty: 'Hard', link: 'https://leetcode.com/problems/trapping-rain-water/' },
      { id: 'ptr6', name: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
      { id: 'ptr7', name: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
      { id: 'ptr8', name: 'Longest Repeating Character Replacement', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-repeating-character-replacement/' },
      { id: 'ptr9', name: 'Permutation in String', difficulty: 'Medium', link: 'https://leetcode.com/problems/permutation-in-string/' },
      { id: 'ptr10', name: 'Minimum Window Substring', difficulty: 'Hard', link: 'https://leetcode.com/problems/minimum-window-substring/' },
      { id: 'ptr11', name: 'Sliding Window Maximum', difficulty: 'Hard', link: 'https://leetcode.com/problems/sliding-window-maximum/' },
      { id: 'ptr12', name: '3Sum Closest', difficulty: 'Medium', link: 'https://leetcode.com/problems/3sum-closest/' },
      { id: 'ptr13', name: 'Is Subsequence', difficulty: 'Easy', link: 'https://leetcode.com/problems/is-subsequence/' },
      { id: 'ptr14', name: '4Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/4sum/' },
      { id: 'ptr15', name: 'Backspace String Compare', difficulty: 'Easy', link: 'https://leetcode.com/problems/backspace-string-compare/' },
      { id: 'ptr16', name: 'Minimum Size Subarray Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-size-subarray-sum/' },
      { id: 'ptr17', name: 'Max Consecutive Ones III', difficulty: 'Medium', link: 'https://leetcode.com/problems/max-consecutive-ones-iii/' },
      { id: 'ptr18', name: 'Find All Anagrams in a String', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/' },
      { id: 'ptr19', name: 'Longest Palindromic Substring', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-palindromic-substring/' },
      { id: 'ptr20', name: 'Valid Palindrome II', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-palindrome-ii/' },
      { id: 'ptr21', name: 'Fruit Into Baskets', difficulty: 'Medium', link: 'https://leetcode.com/problems/fruit-into-baskets/' },
      { id: 'ptr22', name: 'Squares of a Sorted Array', difficulty: 'Easy', link: 'https://leetcode.com/problems/squares-of-a-sorted-array/' },
      { id: 'ptr23', name: 'Sort Array By Parity', difficulty: 'Easy', link: 'https://leetcode.com/problems/sort-array-by-parity/' },
      { id: 'ptr24', name: 'Minimum Operations to Reduce X to Zero', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero/' },
      { id: 'ptr25', name: 'Subarrays with K Different Integers', difficulty: 'Hard', link: 'https://leetcode.com/problems/subarrays-with-k-different-integers/' }
    ]
  },
  {
    id: 'stacks',
    title: 'Stacks, Queues & Monotonic Lists',
    icon: 'splitscreen',
    color: 'text-purple-500 bg-purple-50/50 dark:bg-purple-950/20 border-purple-100 dark:border-purple-900/30',
    problems: [
      { id: 'st1', name: 'Valid Parentheses', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-parentheses/' },
      { id: 'st2', name: 'Min Stack', difficulty: 'Medium', link: 'https://leetcode.com/problems/min-stack/' },
      { id: 'st3', name: 'Evaluate Reverse Polish Notation', difficulty: 'Medium', link: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/' },
      { id: 'st4', name: 'Generate Parentheses', difficulty: 'Medium', link: 'https://leetcode.com/problems/generate-parentheses/' },
      { id: 'st5', name: 'Daily Temperatures', difficulty: 'Medium', link: 'https://leetcode.com/problems/daily-temperatures/' },
      { id: 'st6', name: 'Car Fleet', difficulty: 'Medium', link: 'https://leetcode.com/problems/car-fleet/' },
      { id: 'st7', name: 'Largest Rectangle in Histogram', difficulty: 'Hard', link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },
      { id: 'st8', name: 'Implement Queue using Stacks', difficulty: 'Easy', link: 'https://leetcode.com/problems/implement-queue-using-stacks/' },
      { id: 'st9', name: 'Implement Stack using Queues', difficulty: 'Easy', link: 'https://leetcode.com/problems/implement-stack-using-queues/' },
      { id: 'st10', name: 'Remove All Adjacent Duplicates in String II', difficulty: 'Medium', link: 'https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/' },
      { id: 'st11', name: 'Next Greater Element I', difficulty: 'Easy', link: 'https://leetcode.com/problems/next-greater-element-i/' },
      { id: 'st12', name: 'Next Greater Element II', difficulty: 'Medium', link: 'https://leetcode.com/problems/next-greater-element-ii/' },
      { id: 'st13', name: 'Online Stock Span', difficulty: 'Medium', link: 'https://leetcode.com/problems/online-stock-span/' },
      { id: 'st14', name: 'Simplify Path', difficulty: 'Medium', link: 'https://leetcode.com/problems/simplify-path/' },
      { id: 'st15', name: 'Asteroid Collision', difficulty: 'Medium', link: 'https://leetcode.com/problems/asteroid-collision/' },
      { id: 'st16', name: 'Decode String', difficulty: 'Medium', link: 'https://leetcode.com/problems/decode-string/' },
      { id: 'st17', name: 'Basic Calculator II', difficulty: 'Medium', link: 'https://leetcode.com/problems/basic-calculator-ii/' },
      { id: 'st18', name: 'Basic Calculator', difficulty: 'Hard', link: 'https://leetcode.com/problems/basic-calculator/' },
      { id: 'st19', name: '132 Pattern', difficulty: 'Medium', link: 'https://leetcode.com/problems/132-pattern/' },
      { id: 'st20', name: 'Maximal Rectangle', difficulty: 'Hard', link: 'https://leetcode.com/problems/maximal-rectangle/' },
      { id: 'st21', name: 'Task Scheduler', difficulty: 'Medium', link: 'https://leetcode.com/problems/task-scheduler/' },
      { id: 'st22', name: 'Design Circular Queue', difficulty: 'Medium', link: 'https://leetcode.com/problems/design-circular-queue/' },
      { id: 'st23', name: 'Number of Recent Calls', difficulty: 'Easy', link: 'https://leetcode.com/problems/number-of-recent-calls/' },
      { id: 'st24', name: 'Valid Parenthesis String', difficulty: 'Medium', link: 'https://leetcode.com/problems/valid-parenthesis-string/' },
      { id: 'st25', name: 'Trapping Rain Water II', difficulty: 'Hard', link: 'https://leetcode.com/problems/trapping-rain-water-ii/' }
    ]
  },
  {
    id: 'binarysearch',
    title: 'Binary Search & Dividers',
    icon: 'search',
    color: 'text-teal-500 bg-teal-50/50 dark:bg-teal-950/20 border-teal-100 dark:border-teal-900/30',
    problems: [
      { id: 'bs1', name: 'Binary Search', difficulty: 'Easy', link: 'https://leetcode.com/problems/binary-search/' },
      { id: 'bs2', name: 'Search a 2D Matrix', difficulty: 'Medium', link: 'https://leetcode.com/problems/search-a-2d-matrix/' },
      { id: 'bs3', name: 'Koko Eating Bananas', difficulty: 'Medium', link: 'https://leetcode.com/problems/koko-eating-bananas/' },
      { id: 'bs4', name: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
      { id: 'bs5', name: 'Search in Rotated Sorted Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
      { id: 'bs6', name: 'Time Based Key-Value Store', difficulty: 'Medium', link: 'https://leetcode.com/problems/time-based-key-value-store/' },
      { id: 'bs7', name: 'Median of Two Sorted Arrays', difficulty: 'Hard', link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },
      { id: 'bs8', name: 'First Bad Version', difficulty: 'Easy', link: 'https://leetcode.com/problems/first-bad-version/' },
      { id: 'bs9', name: 'Search Insert Position', difficulty: 'Easy', link: 'https://leetcode.com/problems/search-insert-position/' },
      { id: 'bs10', name: 'Peak Index in a Mountain Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/peak-index-in-a-mountain-array/' },
      { id: 'bs11', name: 'Find Peak Element', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-peak-element/' },
      { id: 'bs12', name: 'Find First and Last Position of Element in Sorted Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/' },
      { id: 'bs13', name: 'Single Element in a Sorted Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/single-element-in-a-sorted-array/' },
      { id: 'bs14', name: 'Search in Rotated Sorted Array II', difficulty: 'Medium', link: 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/' },
      { id: 'bs15', name: 'Capacity To Ship Packages Within D Days', difficulty: 'Medium', link: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/' },
      { id: 'bs16', name: 'Arranging Coins', difficulty: 'Easy', link: 'https://leetcode.com/problems/arranging-coins/' },
      { id: 'bs17', name: 'Guess Number Higher or Lower', difficulty: 'Easy', link: 'https://leetcode.com/problems/guess-number-higher-or-lower/' },
      { id: 'bs18', name: 'Valid Perfect Square', difficulty: 'Easy', link: 'https://leetcode.com/problems/valid-perfect-square/' },
      { id: 'bs19', name: 'Divide Two Integers', difficulty: 'Medium', link: 'https://leetcode.com/problems/divide-two-integers/' },
      { id: 'bs20', name: 'Split Array Largest Sum', difficulty: 'Hard', link: 'https://leetcode.com/problems/split-array-largest-sum/' },
      { id: 'bs21', name: 'Aggressive Cows (SPOJ / Similar)', difficulty: 'Medium', link: 'https://leetcode.com/problems/magnetic-force-between-two-balls/' },
      { id: 'bs22', name: 'Book Allocation Problem (Similar)', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/' },
      { id: 'bs23', name: 'Find in Mountain Array', difficulty: 'Hard', link: 'https://leetcode.com/problems/find-in-mountain-array/' },
      { id: 'bs24', name: 'Kth Smallest Element in a Sorted Matrix', difficulty: 'Medium', link: 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/' },
      { id: 'bs25', name: 'Median of a Row Wise Sorted Matrix', difficulty: 'Hard', link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' }
    ]
  },
  {
    id: 'linkedlists',
    title: 'Linked Lists & Cycles',
    icon: 'format_list_bulleted',
    color: 'text-pink-500 bg-pink-50/50 dark:bg-pink-950/20 border-pink-100 dark:border-pink-900/30',
    problems: [
      { id: 'll1', name: 'Reverse Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/reverse-linked-list/' },
      { id: 'll2', name: 'Merge Two Sorted Lists', difficulty: 'Easy', link: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
      { id: 'll3', name: 'Reorder List', difficulty: 'Medium', link: 'https://leetcode.com/problems/reorder-list/' },
      { id: 'll4', name: 'Remove Nth Node From End of List', difficulty: 'Medium', link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
      { id: 'll5', name: 'Copy List with Random Pointer', difficulty: 'Medium', link: 'https://leetcode.com/problems/copy-list-with-random-pointer/' },
      { id: 'll6', name: 'Add Two Numbers', difficulty: 'Medium', link: 'https://leetcode.com/problems/add-two-numbers/' },
      { id: 'll7', name: 'Linked List Cycle', difficulty: 'Easy', link: 'https://leetcode.com/problems/linked-list-cycle/' },
      { id: 'll8', name: 'Linked List Cycle II', difficulty: 'Medium', link: 'https://leetcode.com/problems/linked-list-cycle-ii/' },
      { id: 'll9', name: 'Find the Duplicate Number', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-the-duplicate-number/' },
      { id: 'll10', name: 'LRU Cache', difficulty: 'Medium', link: 'https://leetcode.com/problems/lru-cache/' },
      { id: 'll11', name: 'Merge k Sorted Lists', difficulty: 'Hard', link: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
      { id: 'll12', name: 'Reverse Nodes in k-Group', difficulty: 'Hard', link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/' },
      { id: 'll13', name: 'Palindrome Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/palindrome-linked-list/' },
      { id: 'll14', name: 'Remove Linked List Elements', difficulty: 'Easy', link: 'https://leetcode.com/problems/remove-linked-list-elements/' },
      { id: 'll15', name: 'Delete Node in a Linked List', difficulty: 'Easy', link: 'https://leetcode.com/problems/delete-node-in-a-linked-list/' },
      { id: 'll16', name: 'Intersection of Two Linked Lists', difficulty: 'Easy', link: 'https://leetcode.com/problems/intersection-of-two-linked-lists/' },
      { id: 'll17', name: 'Remove Duplicates from Sorted List', difficulty: 'Easy', link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list/' },
      { id: 'll18', name: 'Odd Even Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/odd-even-linked-list/' },
      { id: 'll19', name: 'Sort List', difficulty: 'Medium', link: 'https://leetcode.com/problems/sort-list/' },
      { id: 'll20', name: 'Rotate List', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotate-list/' },
      { id: 'll21', name: 'Partition List', difficulty: 'Medium', link: 'https://leetcode.com/problems/partition-list/' },
      { id: 'll22', name: 'Remove Duplicates from Sorted List II', difficulty: 'Medium', link: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/' },
      { id: 'll23', name: 'Swap Nodes in Pairs', difficulty: 'Medium', link: 'https://leetcode.com/problems/swap-nodes-in-pairs/' },
      { id: 'll24', name: 'LFU Cache', difficulty: 'Hard', link: 'https://leetcode.com/problems/lfu-cache/' },
      { id: 'll25', name: 'Design Linked List', difficulty: 'Medium', link: 'https://leetcode.com/problems/design-linked-list/' }
    ]
  },
  {
    id: 'trees',
    title: 'Trees & Tries',
    icon: 'account_tree',
    color: 'text-amber-500 bg-amber-50/50 dark:bg-amber-950/20 border-amber-100 dark:border-amber-900/30',
    problems: [
      { id: 'tr1', name: 'Invert Binary Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/invert-binary-tree/' },
      { id: 'tr2', name: 'Maximum Depth of Binary Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
      { id: 'tr3', name: 'Diameter of Binary Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
      { id: 'tr4', name: 'Balanced Binary Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/balanced-binary-tree/' },
      { id: 'tr5', name: 'Same Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/same-tree/' },
      { id: 'tr6', name: 'Subtree of Another Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/subtree-of-another-tree/' },
      { id: 'tr7', name: 'Lowest Common Ancestor of a Binary Search Tree', difficulty: 'Medium', link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/' },
      { id: 'tr8', name: 'Binary Tree Level Order Traversal', difficulty: 'Medium', link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
      { id: 'tr9', name: 'Binary Tree Right Side View', difficulty: 'Medium', link: 'https://leetcode.com/problems/binary-tree-right-side-view/' },
      { id: 'tr10', name: 'Count Good Nodes in Binary Tree', difficulty: 'Medium', link: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/' },
      { id: 'tr11', name: 'Validate Binary Search Tree', difficulty: 'Medium', link: 'https://leetcode.com/problems/validate-binary-search-tree/' },
      { id: 'tr12', name: 'Kth Smallest Element in a BST', difficulty: 'Medium', link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
      { id: 'tr13', name: 'Construct Binary Tree from Preorder and Inorder Traversal', difficulty: 'Medium', link: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
      { id: 'tr14', name: 'Binary Tree Maximum Path Sum', difficulty: 'Hard', link: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
      { id: 'tr15', name: 'Serialize and Deserialize Binary Tree', difficulty: 'Hard', link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },
      { id: 'tr16', name: 'Binary Tree Inorder Traversal', difficulty: 'Easy', link: 'https://leetcode.com/problems/binary-tree-inorder-traversal/' },
      { id: 'tr17', name: 'Binary Tree Preorder Traversal', difficulty: 'Easy', link: 'https://leetcode.com/problems/binary-tree-preorder-traversal/' },
      { id: 'tr18', name: 'Binary Tree Postorder Traversal', difficulty: 'Easy', link: 'https://leetcode.com/problems/binary-tree-postorder-traversal/' },
      { id: 'tr19', name: 'Merge Two Binary Trees', difficulty: 'Easy', link: 'https://leetcode.com/problems/merge-two-binary-trees/' },
      { id: 'tr20', name: 'Path Sum', difficulty: 'Easy', link: 'https://leetcode.com/problems/path-sum/' },
      { id: 'tr21', name: 'Lowest Common Ancestor of a Binary Tree', difficulty: 'Medium', link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/' },
      { id: 'tr22', name: 'Populating Next Right Pointers in Each Node', difficulty: 'Medium', link: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/' },
      { id: 'tr23', name: 'Convert Sorted Array to Binary Search Tree', difficulty: 'Easy', link: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/' },
      { id: 'tr24', name: 'Implement Trie (Prefix Tree)', difficulty: 'Medium', link: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
      { id: 'tr25', name: 'Design Add and Search Words Data Structure', difficulty: 'Medium', link: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
      { id: 'tr26', name: 'Word Search II', difficulty: 'Hard', link: 'https://leetcode.com/problems/word-search-ii/' }
    ]
  },
  {
    id: 'graphs',
    title: 'Graphs & Traversals',
    icon: 'scatter_plot',
    color: 'text-indigo-500 bg-indigo-50/50 dark:bg-indigo-950/20 border-indigo-100 dark:border-indigo-900/30',
    problems: [
      { id: 'gr1', name: 'Number of Islands', difficulty: 'Medium', link: 'https://leetcode.com/problems/number-of-islands/' },
      { id: 'gr2', name: 'Clone Graph', difficulty: 'Medium', link: 'https://leetcode.com/problems/clone-graph/' },
      { id: 'gr3', name: 'Max Area of Island', difficulty: 'Medium', link: 'https://leetcode.com/problems/max-area-of-island/' },
      { id: 'gr4', name: 'Pacific Atlantic Water Flow', difficulty: 'Medium', link: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
      { id: 'gr5', name: 'Surrounded Regions', difficulty: 'Medium', link: 'https://leetcode.com/problems/surrounded-regions/' },
      { id: 'gr6', name: 'Rotting Oranges', difficulty: 'Medium', link: 'https://leetcode.com/problems/rotting-oranges/' },
      { id: 'gr7', name: 'Walls and Gates', difficulty: 'Medium', link: 'https://leetcode.com/problems/walls-and-gates/' },
      { id: 'gr8', name: 'Course Schedule', difficulty: 'Medium', link: 'https://leetcode.com/problems/course-schedule/' },
      { id: 'gr9', name: 'Course Schedule II', difficulty: 'Medium', link: 'https://leetcode.com/problems/course-schedule-ii/' },
      { id: 'gr10', name: 'Redundant Connection', difficulty: 'Medium', link: 'https://leetcode.com/problems/redundant-connection/' },
      { id: 'gr11', name: 'Number of Connected Components in an Undirected Graph', difficulty: 'Medium', link: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/' },
      { id: 'gr12', name: 'Graph Valid Tree', difficulty: 'Medium', link: 'https://leetcode.com/problems/graph-valid-tree/' },
      { id: 'gr13', name: 'Word Ladder', difficulty: 'Hard', link: 'https://leetcode.com/problems/word-ladder/' },
      { id: 'gr14', name: 'Reconstruct Itinerary', difficulty: 'Hard', link: 'https://leetcode.com/problems/reconstruct-itinerary/' },
      { id: 'gr15', name: 'Min Cost to Connect All Points', difficulty: 'Medium', link: 'https://leetcode.com/problems/min-cost-to-connect-all-points/' },
      { id: 'gr16', name: 'Network Delay Time', difficulty: 'Medium', link: 'https://leetcode.com/problems/network-delay-time/' },
      { id: 'gr17', name: 'Swim in Rising Water', difficulty: 'Hard', link: 'https://leetcode.com/problems/swim-in-rising-water/' },
      { id: 'gr18', name: 'Alien Dictionary', difficulty: 'Hard', link: 'https://leetcode.com/problems/alien-dictionary/' },
      { id: 'gr19', name: 'Cheapest Flights Within K Stops', difficulty: 'Medium', link: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/' },
      { id: 'gr20', name: 'Keys and Rooms', difficulty: 'Medium', link: 'https://leetcode.com/problems/keys-and-rooms/' },
      { id: 'gr21', name: 'All Paths From Source to Target', difficulty: 'Medium', link: 'https://leetcode.com/problems/all-paths-from-source-to-target/' },
      { id: 'gr22', name: 'Flood Fill', difficulty: 'Easy', link: 'https://leetcode.com/problems/flood-fill/' },
      { id: 'gr23', name: 'As Far from Land as Possible', difficulty: 'Medium', link: 'https://leetcode.com/problems/as-far-from-land-as-possible/' },
      { id: 'gr24', name: 'Is Graph Bipartite?', difficulty: 'Medium', link: 'https://leetcode.com/problems/is-graph-bipartite/' },
      { id: 'gr25', name: 'Longest Increasing Path in a Matrix', difficulty: 'Hard', link: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/' }
    ]
  },
  {
    id: 'backtracking',
    title: 'Backtracking & Heaps',
    icon: 'history',
    color: 'text-rose-500 bg-rose-50/50 dark:bg-rose-950/20 border-rose-100 dark:border-rose-900/30',
    problems: [
      { id: 'bk1', name: 'Subsets', difficulty: 'Medium', link: 'https://leetcode.com/problems/subsets/' },
      { id: 'bk2', name: 'Combination Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/combination-sum/' },
      { id: 'bk3', name: 'Permutations', difficulty: 'Medium', link: 'https://leetcode.com/problems/permutations/' },
      { id: 'bk4', name: 'Subsets II', difficulty: 'Medium', link: 'https://leetcode.com/problems/subsets-ii/' },
      { id: 'bk5', name: 'Combination Sum II', difficulty: 'Medium', link: 'https://leetcode.com/problems/combination-sum-ii/' },
      { id: 'bk6', name: 'Word Search', difficulty: 'Medium', link: 'https://leetcode.com/problems/word-search/' },
      { id: 'bk7', name: 'Palindrome Partitioning', difficulty: 'Medium', link: 'https://leetcode.com/problems/palindrome-partitioning/' },
      { id: 'bk8', name: 'Letter Combinations of a Phone Number', difficulty: 'Medium', link: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/' },
      { id: 'bk9', name: 'N-Queens', difficulty: 'Hard', link: 'https://leetcode.com/problems/n-queens/' },
      { id: 'bk10', name: 'Kth Largest Element in an Array', difficulty: 'Medium', link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
      { id: 'bk11', name: 'Top K Frequent Words', difficulty: 'Medium', link: 'https://leetcode.com/problems/top-k-frequent-words/' },
      { id: 'bk12', name: 'Find Median from Data Stream', difficulty: 'Hard', link: 'https://leetcode.com/problems/find-median-from-data-stream/' },
      { id: 'bk13', name: 'K Closest Points to Origin', difficulty: 'Medium', link: 'https://leetcode.com/problems/k-closest-points-to-origin/' },
      { id: 'bk14', name: 'Last Stone Weight', difficulty: 'Easy', link: 'https://leetcode.com/problems/last-stone-weight/' },
      { id: 'bk15', name: 'Merge k Sorted Lists (Heap Method)', difficulty: 'Hard', link: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
      { id: 'bk16', name: 'Sudoku Solver', difficulty: 'Hard', link: 'https://leetcode.com/problems/sudoku-solver/' },
      { id: 'bk17', name: 'Combinations', difficulty: 'Medium', link: 'https://leetcode.com/problems/combinations/' },
      { id: 'bk18', name: 'Permutations II', difficulty: 'Medium', link: 'https://leetcode.com/problems/permutations-ii/' },
      { id: 'bk19', name: 'Beautiful Arrangement', difficulty: 'Medium', link: 'https://leetcode.com/problems/beautiful-arrangement/' },
      { id: 'bk20', name: 'N-Queens II', difficulty: 'Hard', link: 'https://leetcode.com/problems/n-queens-ii/' },
      { id: 'bk21', name: 'Find K Pairs with Smallest Sums', difficulty: 'Medium', link: 'https://leetcode.com/problems/find-k-pairs-with-smallest-sums/' },
      { id: 'bk22', name: 'Kth Largest Element in a Stream', difficulty: 'Easy', link: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/' },
      { id: 'bk23', name: 'Design Twitter', difficulty: 'Medium', link: 'https://leetcode.com/problems/design-twitter/' },
      { id: 'bk24', name: 'Smallest Range Covering Elements from K Lists', difficulty: 'Hard', link: 'https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/' },
      { id: 'bk25', name: 'Swim in Rising Water (Heap Method)', difficulty: 'Hard', link: 'https://leetcode.com/problems/swim-in-rising-water/' }
    ]
  },
  {
    id: 'dp',
    title: 'Dynamic Programming & Knapsacks',
    icon: 'layers',
    color: 'text-violet-500 bg-violet-50/50 dark:bg-violet-950/20 border-violet-100 dark:border-violet-900/30',
    problems: [
      { id: 'dp1', name: 'Climbing Stairs', difficulty: 'Easy', link: 'https://leetcode.com/problems/climbing-stairs/' },
      { id: 'dp2', name: 'Min Cost Climbing Stairs', difficulty: 'Easy', link: 'https://leetcode.com/problems/min-cost-climbing-stairs/' },
      { id: 'dp3', name: 'House Robber', difficulty: 'Medium', link: 'https://leetcode.com/problems/house-robber/' },
      { id: 'dp4', name: 'House Robber II', difficulty: 'Medium', link: 'https://leetcode.com/problems/house-robber-ii/' },
      { id: 'dp5', name: 'Longest Palindromic Substring (DP)', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-palindromic-substring/' },
      { id: 'dp6', name: 'Palindromic Substrings', difficulty: 'Medium', link: 'https://leetcode.com/problems/palindromic-substrings/' },
      { id: 'dp7', name: 'Decode Ways', difficulty: 'Medium', link: 'https://leetcode.com/problems/decode-ways/' },
      { id: 'dp8', name: 'Coin Change', difficulty: 'Medium', link: 'https://leetcode.com/problems/coin-change/' },
      { id: 'dp9', name: 'Maximum Product Subarray', difficulty: 'Medium', link: 'https://leetcode.com/problems/maximum-product-subarray/' },
      { id: 'dp10', name: 'Word Break', difficulty: 'Medium', link: 'https://leetcode.com/problems/word-break/' },
      { id: 'dp11', name: 'Longest Increasing Subsequence', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
      { id: 'dp12', name: 'Partition Equal Subset Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/partition-equal-subset-sum/' },
      { id: 'dp13', name: 'Unique Paths', difficulty: 'Medium', link: 'https://leetcode.com/problems/unique-paths/' },
      { id: 'dp14', name: 'Longest Common Subsequence', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-common-subsequence/' },
      { id: 'dp15', name: 'Best Time to Buy and Sell Stock with Cooldown', difficulty: 'Medium', link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/' },
      { id: 'dp16', name: 'Coin Change II', difficulty: 'Medium', link: 'https://leetcode.com/problems/coin-change-ii/' },
      { id: 'dp17', name: 'Target Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/target-sum/' },
      { id: 'dp18', name: 'Interleaving String', difficulty: 'Medium', link: 'https://leetcode.com/problems/interleaving-string/' },
      { id: 'dp19', name: 'Edit Distance', difficulty: 'Hard', link: 'https://leetcode.com/problems/edit-distance/' },
      { id: 'dp20', name: 'Burst Balloons', difficulty: 'Hard', link: 'https://leetcode.com/problems/burst-balloons/' },
      { id: 'dp21', name: 'Regular Expression Matching', difficulty: 'Hard', link: 'https://leetcode.com/problems/regular-expression-matching/' },
      { id: 'dp22', name: 'Maximal Square', difficulty: 'Medium', link: 'https://leetcode.com/problems/maximal-square/' },
      { id: 'dp23', name: 'Triangle', difficulty: 'Medium', link: 'https://leetcode.com/problems/triangle/' },
      { id: 'dp24', name: 'Minimum Path Sum', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-path-sum/' },
      { id: 'dp25', name: 'Longest Common Substring (Similar)', difficulty: 'Medium', link: 'https://leetcode.com/problems/longest-common-subsequence/' }
    ]
  },
  {
    id: 'greedy',
    title: 'Greedy & Math Optimization',
    icon: 'insights',
    color: 'text-orange-500 bg-orange-50/50 dark:bg-orange-950/20 border-orange-100 dark:border-orange-900/30',
    problems: [
      { id: 'grd1', name: 'Maximum Subarray (Kadanes)', difficulty: 'Easy', link: 'https://leetcode.com/problems/maximum-subarray/' },
      { id: 'grd2', name: 'Jump Game', difficulty: 'Medium', link: 'https://leetcode.com/problems/jump-game/' },
      { id: 'grd3', name: 'Jump Game II', difficulty: 'Medium', link: 'https://leetcode.com/problems/jump-game-ii/' },
      { id: 'grd4', name: 'Gas Station', difficulty: 'Medium', link: 'https://leetcode.com/problems/gas-station/' },
      { id: 'grd5', name: 'Hand of Straights', difficulty: 'Medium', link: 'https://leetcode.com/problems/hand-of-straights/' },
      { id: 'grd6', name: 'Merge Intervals', difficulty: 'Medium', link: 'https://leetcode.com/problems/merge-intervals/' },
      { id: 'grd7', name: 'Insert Interval', difficulty: 'Medium', link: 'https://leetcode.com/problems/insert-interval/' },
      { id: 'grd8', name: 'Non-overlapping Intervals', difficulty: 'Medium', link: 'https://leetcode.com/problems/non-overlapping-intervals/' },
      { id: 'grd9', name: 'Meeting Rooms', difficulty: 'Easy', link: 'https://leetcode.com/problems/meeting-rooms/' },
      { id: 'grd10', name: 'Meeting Rooms II', difficulty: 'Medium', link: 'https://leetcode.com/problems/meeting-rooms-ii/' },
      { id: 'grd11', name: 'Partition Labels', difficulty: 'Medium', link: 'https://leetcode.com/problems/partition-labels/' },
      { id: 'grd12', name: 'Valid Parenthesis String', difficulty: 'Medium', link: 'https://leetcode.com/problems/valid-parenthesis-string/' },
      { id: 'grd13', name: 'Candy', difficulty: 'Hard', link: 'https://leetcode.com/problems/candy/' },
      { id: 'grd14', name: 'Two City Scheduling', difficulty: 'Medium', link: 'https://leetcode.com/problems/two-city-scheduling/' },
      { id: 'grd15', name: 'Assign Cookies', difficulty: 'Easy', link: 'https://leetcode.com/problems/assign-cookies/' },
      { id: 'grd16', name: 'Queue Reconstruction by Height', difficulty: 'Medium', link: 'https://leetcode.com/problems/queue-reconstruction-by-height/' },
      { id: 'grd17', name: 'Lemonade Change', difficulty: 'Easy', link: 'https://leetcode.com/problems/lemonade-change/' },
      { id: 'grd18', name: 'Boats to Save People', difficulty: 'Medium', link: 'https://leetcode.com/problems/boats-to-save-people/' },
      { id: 'grd19', name: 'Reducing Dishes', difficulty: 'Hard', link: 'https://leetcode.com/problems/reducing-dishes/' },
      { id: 'grd20', name: 'Minimum Number of Arrows to Burst Balloons', difficulty: 'Medium', link: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/' },
      { id: 'grd21', name: 'Number of 1 Bits', difficulty: 'Easy', link: 'https://leetcode.com/problems/number-of-1-bits/' },
      { id: 'grd22', name: 'Counting Bits', difficulty: 'Easy', link: 'https://leetcode.com/problems/counting-bits/' },
      { id: 'grd23', name: 'Reverse Bits', difficulty: 'Easy', link: 'https://leetcode.com/problems/reverse-bits/' },
      { id: 'grd24', name: 'Missing Number', difficulty: 'Easy', link: 'https://leetcode.com/problems/missing-number/' },
      { id: 'grd25', name: 'Sum of Two Integers', difficulty: 'Medium', link: 'https://leetcode.com/problems/sum-of-two-integers/' }
    ]
  }
];
